### ISSUE TITLE
Command switch to get yum to update security advisories only

### ISSUE THREAD

**Issue by paulmaunders** [wied03/centos-package-cron#12]
Since yum security doesn't work properly on CentOS, I am finding your tool really useful - so thanks for creating it :)

I have been using something like the following one liner to try to update all the security advisory packages on a system from your command:

```
centos-package-cron --output stdout --forceold | pcregrep -M 'Packages:[^:]*' | grep -o "[^* ]*" | grep -v 'Packages:' | grep -v 'References' | sort | uniq | xargs yum -y update
```

However this is a bit clunky and requires pcre-tools to be installed. I was wondering how difficult it would be for you to add a command line option to centos-package-cron to achieve the same result? (e.g. applying the security updates)

**Comment by wied03** [comment]
@paulmaunders - Thanks! In this case, doing the updates themselves is something I view as outside the scope of this tool. I think it should be done by a CM tool (Chef, Puppet, etc.).

That said, something that has been on the wish list in the back of my head is to add XML or JSON to the output format list. That way it would be easier to parse and do what you want.

Would that help?

**Comment by paulmaunders** [comment]
Perhaps even just a having flag to return the package names only in text format?

**Comment by wied03** [comment]
Would you be opposed to JSON/XML? That way I don't have to add a bunch of command line switches to control what's displayed/formatted (security vs. general updates). Anyone could pick from the response what they needed.

**Comment by paulmaunders** [comment]
Either XML or JSON would be fine as we could quite easily parse that!

**Comment by wied03** [comment]
I started the process on this in a branch but haven't had the time to keep going on it.

**Comment by stephane-martin** [comment]
I'll take this one if you'd like. I already added JSON output to syslog in this branch: https://github.com/stephane-martin/centos-package-cron/tree/syslog_output

**Comment by wied03** [comment]
I'd appreciate the help. As long as unit tests are added and the existing ones don't break :)

**Comment by stephane-martin** [comment]
Sure. Basically i think that we could have three switches: --json (output results to stdout as JSON), --mail (send results by email), --syslog (publish results to syslog). The switches would be cumulative, not exclusive.

**Comment by wied03** [comment]
I started a branch here https://github.com/wied03/centos-package-cron/commits/features/return_code_email and I was going to just remove email entirely and let people use sendmail/mailx/cronwrapper/etc. but then of course I got busy with the day job.

**Comment by stephane-martin** [comment]
Well, if you want to remove email, then it's probably better to keep a "--output" switch that specifies the format to print to stdout (json or text). --syslog could be added to also send alerts to syslog.

**Comment by wied03** [comment]
@stephane-martin - Are you still working on this?

**Comment by stephane-martin** [comment]
not on the last two weeks, but still interested for sure. i'll have some 
time to code at the end of feb.

**Comment by wied03** [comment]
@stephane-martin - I'll standby on this one and when you get the time, we can see where you end up. Should I remove the (incomplete) branch I referenced above?

**Comment by FTBZ** [comment]
Very interested in the ability to extract packages/erratas available by command line operation.

**Comment by wied03** [comment]
Now that someone submitted a JSON PR, closing this
