### ISSUE TITLE
Support proxy parameter from /etc/yum.conf

### ISSUE THREAD

**Issue by stephane-martin** [wied03/centos-package-cron#16]
Hello,

When centos-package-cron downloads the list of advisories (`urllib2.urlopen('https://cefs.steve-meier.de/errata.latest.xml')`), it would be nice if it could use the proxy parameter that may be present in `/etc/yum.conf`. This way servers that do not face internet could use centos-package-cron without dealing with not-so-robust HTTP_PROXY environment variable.

`urlopen` supports a `proxies` kw argument to do that.

Thanks for the good work !

**Comment by wied03** [comment]
Seems like a good idea. Just need the time: /

**Comment by wied03** [comment]
I put this in the CHANGELOG for the next release (1.0.9)
