### ISSUE TITLE
No security advisory reported

### ISSUE THREAD

**Issue by stephane-martin** [wied03/centos-package-cron#18]
Hello,

I installed CentOS 6 in a LXC container one month ago.

```bash
# cat /etc/centos-release
CentOS release 6.8 (Final)
```

Strangely, after one month, there is no security advisory reported by centos-package-cron.

I think the problem lies in `_advisoryPackageMeantForCurrentOs`.

```python
def _advisoryPackageMeantForCurrentOs(self, advisory_package):
    os_version = self.os_fetcher.get_mid_level_version()
    os_version = os_version.replace('.', '_')    # ===> "6_8"
    regexs = [r'.*el'+os_version+'.*']           # ===> does not match with advisory_package.release
                                                 # as typically release is something like "el6"

    if re.match(r'\d+_0', os_version):           # ===> does not match
        top_level_version = self.os_fetcher.get_top_level_version()      # not executed
        regexs.append(r'.*el'+top_level_version+'(?!_).*')               # not executed
```

I'm suspicious about `re.match(r'\d+_0', os_version)`. 

Maybe it should be something like `re.match(r'\d+_\d', os_version)` instead ?

**Comment by wied03** [comment]
Hmm. The integration tests use 6.7 and I believe they ensure some output. I'll check now.

**Comment by wied03** [comment]
I got quite a lot of updates with the 6.7 Docker image that's in this repo. Maybe something is different about 6.8?:

centos-package-cron --output stdout
```
Loaded plugins: fastestmirror
The following security advisories exist for installed packages:

Advisory ID: CESA-2015--1981
Severity: Critical
Packages:
* nss-sysinit-3.18.0-5.3.el6_6
* nss-tools-3.18.0-5.3.el6_6
* nspr-4.10.8-1.el6_6
* nss-3.18.0-5.3.el6_6
* nss-util-3.18.0-1.el6_6
References:
* https://rhn.redhat.com/errata/RHSA-2015-1981.html
* http://lists.centos.org/pipermail/centos-announce/2015-November/021464.html
* http://lists.centos.org/pipermail/centos-announce/2015-November/021465.html
* http://lists.centos.org/pipermail/centos-announce/2015-November/021466.html
* http://lists.centos.org/pipermail/centos-announce/2015-November/021468.html
* http://lists.centos.org/pipermail/centos-announce/2015-November/021469.html
* http://lists.centos.org/pipermail/centos-announce/2015-November/021470.html

Advisory ID: CESA-2016--0175
Severity: Critical
Packages:
* glibc-2.12-1.166.el6
* glibc-common-2.12-1.166.el6
References:
* https://rhn.redhat.com/errata/RHSA-2016-0175.html
* http://lists.centos.org/pipermail/centos-announce/2016-February/021668.html
...
The following packages are available for updating:

audit-libs-2.4.5-3.el6 from base
bash-4.1.2-41.el6_8 from updates
bind-libs-9.8.2-0.47.rc1.el6_8.4 from updates
bind-utils-9.8.2-0.47.rc1.el6_8.4 from updates
binutils-2.20.51.0.2-5.44.el6 from base
ca-certificates-2015.2.6-65.0.1.el6_7 from base
centos-release-6-8.el6.centos.12.3 from base
chkconfig-1.3.49.5-1.el6 from base
...
Change logs for available package updates:

audit-libs-2.4.5-3.el6
Unable to parse changelog for package audit-libs version 2.4.5 release 3.el6

bash-4.1.2-41.el6_8
Unable to parse changelog for package bash version 4.1.2 release 41.el6_8

bind-libs-9.8.2-0.47.rc1.el6_8.4

```

**Comment by wied03** [comment]
When I run against 6.8 as root, I can replicate the problem you're seeing.

When I run as non-root, I get a permission denied error which is unusual.
```
Loaded plugins: fastestmirror, ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/Installtid'
```

**Comment by stephane-martin** [comment]
Take **CESA-2017--0036** for example.
In `errata.latest.xml` we see it impacts `kernel-2.6.32-642.13.1.el6.i686.rpm`

On the Centos server I have:

```bash
# yum list installed | grep kernel
kernel.x86_64                     2.6.32-642.11.1.el6            @updates
```
But for that advisory `_advisoryPackageMeantForCurrentOs(self, advisory_package)` would return `False`.

**Comment by wied03** [comment]
I replicated this in the unit test fairly easily. That said, how should the code differentiate between a package for 6.0 or for any 6.x release? It sounds like what you're saying that el6 applies to any 6.x version.

**Comment by stephane-martin** [comment]
It sounds like what you're saying that el6 applies to any 6.x version.

I don't have enough CentOS experience to be sure.

Let's look at packages suffix on my testing CentOS 6.8 server:

```bash
$ yum list installed | grep el6 | sed -n 's/.*\(el6\S*\).*/\1/p' | sort | uniq
el6
el6_0
el6_0.1
el6_2
el6_4.1
el6_5
el6_5.1
el6_5.2
el6_6
el6_6.2
el6_7
el6_7.1
el6_7.2
el6_7.3
el6_8
el6_8.1
el6_8.2
el6_8.3
el6.centos
el6.centos.1
el6.centos.12.3
```

So yes, it looks like a 6.8 server has installed RPM packages from all the previous 6.X versions.

**Comment by stephane-martin** [comment]
So in `advisoryPackageMeantForCurrentOs` i would just search for the string 'el6' inside teh advisory, and nothing more.

**Comment by wied03** [comment]
I haven't forgotten about this. Just need to find time!

**Comment by wied03** [comment]
Branch - https://github.com/wied03/centos-package-cron/tree/bugfixes/18

**Comment by wied03** [comment]
@stephane-martin - the code in the https://github.com/wied03/centos-package-cron/tree/bugfixes/18 seems to fix the issue from my testing. can you have a look and confirm?

**Comment by wied03** [comment]
Done
