### ISSUE TITLE
Upgrading to higher major versions or not?

### ISSUE THREAD

**Issue by stephengeller** [wied03/centos-package-cron#23]
Hi,

The current implementation reports that upgrades are required for some of our packages, however the package stated to upgrade to is a different major version to our own.

We are wondering whether the tool should recommend upgrading to higher major versions of packages or not?

Thanks,

Stephen

**Comment by wied03** [comment]
@stephengeller - This tool does not make the recommendations. It just correlates security data with yum update data. You should look into yum to answer your question.
