### ISSUE TITLE
Reporting security updates required but no updates available

### ISSUE THREAD

**Issue by lb1f** [wied03/centos-package-cron#27]
I wrote a script to utilise centos-package-cron as a tool to report into PRTG the status of the Cent OS servers I look after and it's been working fine, but over the weekend all my servers started reporting requiring updates.

I've checked on the servers, and there are no outstanding updates.

This is the script I wrote from a modified last update script: https://github.com/lb1f/prtg-sensor-last-yum-update/blob/master/yum-outstanding-security-updates-check.sh

**Comment by wied03** [comment]
Maybe some day I'll get some time to work on this.

**Comment by lb1f** [comment]
Problem didn't go away, unfortunately. I know you're unable to look at this, but I wanted to at least update the thread. I'm not sure why specifically these updates are being highlighted whereas previous updates have been fine.

**Comment by lb1f** [comment]
The problem has now gone away. I don't know what the cause was, or why it's now working. My only assumption was something in the feed breaking it which has now passed.
