### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by roidelapluie** [wied03/centos-package-cron#7]
```
# centos-package-cron 
Traceback (most recent call last):
  File "/usr/bin/centos-package-cron", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by roidelapluie** [comment]
It's missing python-setuptools

**Comment by wied03** [comment]
Sorry about that. That's what I get for testing the build and install in the same VM/container. I separated that to catch any future issues and added setuptools as a runtime dependency as well.

New source RPM link - https://github.com/wied03/centos-package-cron/releases/download/releases%2F1.0.7.2/centos-package-cron-1.0.7-2.el7.centos.src.rpm
