### ISSUE TITLE
--skipold false argument doesn't work

### ISSUE THREAD

**Issue by paulmaunders** [wied03/centos-package-cron#8]
The first time I run the command, I get expected output...

```
[root@host ~]# centos-package-cron --output stdout --skipold false
oading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: s3-mirror-eu-west-1.fedoraproject.org
 * extras: ftp.heanet.ie
 * remi-safe: remi.check-update.co.uk
 * updates: ftp.heanet.ie
The following security advisories exist for installed packages:

Advisory ID: CESA-2016--0370
(snip)
```

However, if I run it another time with _--skipold false_ set, it doesn't give me any security advisories output:

```
[root@host ~]# centos-package-cron --output stdout --skipold false
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: s3-mirror-eu-west-1.fedoraproject.org
 * extras: ftp.heanet.ie
 * remi-safe: remi.check-update.co.uk
 * updates: ftp.heanet.ie
[root@host ~]#
```
If I manually delete the sqllite database and run again, the advisory output returns.

```
[root@host ~]# mv /var/lib/centos-package-cron/already_annoyed.sqlite /var/lib/centos-package-cron/already_annoyed.sqlite.old```

**Comment by wied03** [comment]
I'm guessing the boolean/argparse logic is not working there. I'll take a look when I get a chance.

**Comment by paulmaunders** [comment]
According to a comment on this thread https://github.com/spotify/luigi/issues/193 "BooleanParameters work as False unless the switch is set in which case they are True"

**Comment by wied03** [comment]
I've got a fix on the way for this one too

**Comment by wied03** [comment]
Fixed in master, will crank out a new release with this soon
