### ISSUE TITLE
Script fails when redirecting output to a file

### ISSUE THREAD

**Issue by paulmaunders** [wied03/centos-package-cron#9]
I would like to capture the output of the script to a file, however when I do so it causes an execution error:

```
[root@host ~]# centos-package-cron --output stdout > security-updates.txt
Traceback (most recent call last):
  File "/bin/centos-package-cron", line 9, in <module>
    load_entry_point('centos-package-cron==1.0.7.2', 'console_scripts', 'centos-package-cron')()
  File "/usr/lib/python2.7/site-packages/centos_package_cron/command_line.py", line 33, in main
    print report_content
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10095-10096: ordinal not in range(128)
```

From reading [this](http://stackoverflow.com/questions/31137552/unicodeencodeerror-ascii-codec-cant-encode-character-at-special-name) it suggested it can be fixed by adding the following lines to the command_line.py script:

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

I tested it and it seems to work, so I will create a pull request with the changes.

**Comment by paulmaunders** [comment]
Pull request: https://github.com/wied03/centos-package-cron/pull/10

**Comment by wied03** [comment]
Fixed via PR
